### ISSUE TITLE
5.2.5 having s3 auth issues on yandex cloud

### ISSUE THREAD

**Issue by zznty** [emgarten/Sleet#182]
hello, after upgrading to sleet 5.2.5 i'm unable to auth into a s3 bucket on yandex cloud with error:
```
[Amazon.S3.AmazonS3Exception] The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

however forcing it to use 5.1.3 had the issue resolved for now.

sleet config:
```yml
- name: Push Nuget Package
  env:
    SLEET_FEED_TYPE: s3
    SLEET_FEED_PATH: https://nuget.storage.yandexcloud.net
    SLEET_FEED_BUCKETNAME: nuget
    SLEET_FEED_SERVICEURL: https://storage.yandexcloud.net
    SLEET_FEED_ACCESSKEYID: ${{ secrets.S3_KEY_ID }}
    SLEET_FEED_SECRETACCESSKEY: ${{ secrets.S3_KEY }}
  run: sleet push .
```
